[package]
name = "atra"
version = "0.1.0"
edition = "2021"

# https://en.wikipedia.org/wiki/Erigone_atra

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Async
futures = "0.3"
tokio = { version="1.35", features = ["rt-multi-thread", "macros", "time", "fs", "io-util", "signal"] }
tokio-stream = "0.1"
tokio-util = "0.7"
async-trait = "0.1"

# Downloading data
reqwest = { version = "0.12", features = ["brotli", "gzip", "deflate", "stream", "cookies"] }
reqwest-middleware = "0.3"
http-cache-reqwest = "0.14"
ua_generator = "0.5"
tempfile = "3.10"

# Webdrivers
chromiumoxide = { version = "0.7", optional = true, features = ["tokio-runtime", "bytes"], default-features = false }

# Configuration and Init
clap = { version = "4", features = ["derive"] }
config = { version = "0.14" }
notify = "6.1"

# On disk
queue-file = "1.4"
rocksdb = { version = "0", features = ["multi-threaded-cf" ] }
camino = { version = "1.1", features = ["serde1"] }
camino-tempfile = "1.1"

# Serialisation
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_bytes = "0.11"
serde_yaml = "0.9"
bincode = "1.3"
#ron = "0.8"

# Output formats
rio_api = "0.8"
rio_turtle = "0.8"

# Hashing
twox-hash = "1.6"
fuzzyhash = "0.2"

# Encoding
flate2 = "1.0"
data-encoding = "2.5"

# Identifier
uuid = { version = "1.7", features = ["serde", "v4", "v5", "fast-rng"] }
time = { version = "0.3", features = ["serde", "serde-human-readable", "formatting"] }
#chrono = "0.4"

# Basics
regex = "1.10"
rand = "0.8"
itertools = "0.13"
url = { version = "2.5", features = ["serde"] }
const_format = "0"
deranged = { version = "0.3", features = ["serde"] }
float-cmp = "0.9.0"
#aho-corasick = "1"

# Static stuff
#once_cell = "1.19"

# Memory stuff
smallvec = { version = "1.13", features = ["serde", "const_new", "const_generics", "write", "union"] }
compact_str = { version = "0.8", features = ["serde", "bytes"] }
case_insensitive_string = { version = "0.2", features = ["serde"] }

# Data structures
indexmap = "2.2"
#lru = "0.12"
moka = { version = "0.12", features = ["future"] }
bytes = { version = "1.5", features = ["serde", "default"] }
yada = "0.5"
#phf = { version = "0.11.2", features = ["macros"] }
state = "0.6"

# Delegating
delegate = "0.12"

# Enum extensions
strum = { version = "0.26", features = ["derive"] }
num_enum = "0.7"
enum-iterator = "2.0"

# Bits and bytes
memchr = "2"
ubyte = "0.10"
byteorder = "1"

# Macros
paste = "1"
sealed = "0"

# Logging
log = { version = "0.4", features = ["serde"] }
log4rs = { version = "1.3" }

# Enviroment
num_cpus = "1"
sys-info = "0.9"

# Errors
thiserror = "1.0"
anyhow = "1.0"

# Cluster
# https://crates.io/crates/paxakos

# Scraping
scraper = "0.18"
texting_robots = "0.2"
sitemap = "0.4"
linkify = "0.10"
ress = "0"
mime = "0.3"
encoding_rs = { version = "0.8", features = ["serde"] }
chardetng = "0.1"
#publicsuffix = "2.2"
psl = "2"
file-format = { git = "https://github.com/FelixEngl/file-format.git", branch = "main", features = ["reader", "serde", "extended-enums", "from-all"] }


# Parsing
nom = "7"
unescaper = "0.1"

# Archive
tar = "0.4"

# Text processing
unicode-normalization = { version = "0.1", optional = true }
unicode-segmentation = { version = "1.11", optional = true }

## Stemming of data
rust-stemmers = { version = "1", optional = true }
isolang = { version = "2.4", optional = true }

# File formats
csv = { version = "1.3", optional = true }

# GDPR
## SVM
liblinear = { path= "external/liblinear/crates/liblinear", optional = true }
## Errors of SVM...
#failure = { version = "0.1", optional = true }

#suffix = { version = "1.3", optional = true }

# TOR
# libtor-sys = "47.13.0"
# torut = "0.2.1"

[dev-dependencies]
scopeguard = "1.2"
mockall = "0.12"
lipsum = "0.9"

[build-dependencies]
#file-format = { git = "https://github.com/FelixEngl/file-format.git", branch = "main", features = ["reader", "extended-enums"] }
paste = "1.0"
#phf_codegen = "0.11"
isolang = "2.4"
tinyjson = "2.5"
flate2 = "1.0"
#curl = "0.4"
#serde = "1.0"
#serde_json = "1.0"
#time = { version = "0.3", features = ["serde", "serde-human-readable", "formatting"] }

# cc = "1.0"

[features]
text_processing = ["dep:unicode-normalization", "dep:unicode-segmentation", "dep:rust-stemmers", "dep:isolang"]
chrome = ["dep:chromiumoxide"]
gdpr = ["dep:liblinear", "text_processing", "dep:csv"]